package renderer

import (
	"fmt"
	"sort"
	"strings"
)

// renderPlatformDocs generates a complete docs site from aggregated platform data.
func renderPlatformDocs(data map[string]interface{}) []DocsPage {
	var pages []DocsPage

	pages = append(pages, DocsPage{
		Path:    "index.md",
		Content: renderPlatformIndexDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "platform-architecture.md",
		Content: renderPlatformArchDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "network-topology.md",
		Content: renderPlatformNetworkDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "rbac-surface.md",
		Content: renderPlatformRBACDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "secrets-inventory.md",
		Content: renderPlatformSecretsDocPage(data),
	})

	// Per-component deep dive pages (dedup by component name)
	componentDataList := getSlice(data, "component_data")
	seenComps := make(map[string]bool)
	for _, compData := range componentDataList {
		compName := getStr(compData, "component", "")
		if compName == "" || seenComps[compName] {
			continue
		}
		seenComps[compName] = true
		compPages := renderComponentDocs(compData, "components/"+sanitizeID(compName))
		pages = append(pages, compPages...)
	}

	return pages
}

// --- Platform index page ---

func renderPlatformIndexDocPage(data map[string]interface{}) string {
	var b strings.Builder

	platformName := getStr(data, "platform", "Platform")
	components := getStringSlice(data, "components")
	crds := getSlice(data, "crds")
	services := getSlice(data, "services")
	secrets := getSlice(data, "secrets_referenced")
	rbacRoles := getSlice(data, "rbac_cluster_roles")
	depGraph := getSlice(data, "dependency_graph")

	b.WriteString(fmt.Sprintf("# %s Platform Analysis\n\n", platformName))
	b.WriteString("*Generated by rhoai-architecture-analyzer. All data produced by deterministic static analysis.*\n\n")

	// Summary
	b.WriteString("## Platform Summary\n\n")
	b.WriteString("| Metric | Count |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Components | %d |\n", len(components)))
	b.WriteString(fmt.Sprintf("| CRDs | %d |\n", len(crds)))
	b.WriteString(fmt.Sprintf("| Services | %d |\n", len(services)))
	b.WriteString(fmt.Sprintf("| Secrets | %d |\n", len(secrets)))
	b.WriteString(fmt.Sprintf("| Cluster Roles | %d |\n", len(rbacRoles)))
	b.WriteString(fmt.Sprintf("| Cross-Component Dependencies | %d |\n", len(depGraph)))
	b.WriteString("\n")

	// Component dependency graph
	b.WriteString("## Component Dependency Graph\n\n")
	b.WriteString(renderPlatformDepGraphMermaid(data))
	b.WriteString("\n")

	// Component list
	b.WriteString("## Components Analyzed\n\n")
	if len(components) > 0 {
		sorted := make([]string, len(components))
		copy(sorted, components)
		sort.Strings(sorted)

		// Count CRDs per component
		crdCounts := make(map[string]int)
		for _, crd := range crds {
			owner := getStr(crd, "owner", "")
			crdCounts[owner]++
		}

		b.WriteString("| Component | CRDs |\n")
		b.WriteString("|-----------|------|\n")
		for _, comp := range sorted {
			count := crdCounts[comp]
			b.WriteString(fmt.Sprintf("| %s | %d |\n", comp, count))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderPlatformDepGraphMermaid builds a clean, deduplicated dependency graph.
func renderPlatformDepGraphMermaid(data map[string]interface{}) string {
	var b strings.Builder

	components := getStringSlice(data, "components")
	depGraph := getSlice(data, "dependency_graph")

	b.WriteString("```mermaid\n")
	b.WriteString("graph TD\n")
	b.WriteString("    classDef operator fill:#3498db,stroke:#2980b9,color:#fff\n")
	b.WriteString("    classDef serving fill:#9b59b6,stroke:#8e44ad,color:#fff\n")
	b.WriteString("    classDef data fill:#e74c3c,stroke:#c0392b,color:#fff\n")
	b.WriteString("    classDef infra fill:#95a5a6,stroke:#7f8c8d,color:#fff\n")
	b.WriteString("    classDef ui fill:#2ecc71,stroke:#27ae60,color:#fff\n\n")

	// Emit component nodes
	crdCounts := make(map[string]int)
	for _, crd := range getSlice(data, "crds") {
		owner := getStr(crd, "owner", "")
		crdCounts[owner]++
	}

	emittedNodes := make(map[string]bool)
	for _, comp := range components {
		cid := sanitizeID(comp)
		if emittedNodes[cid] {
			continue
		}
		emittedNodes[cid] = true
		crdCount := crdCounts[comp]
		label := escapeLabel(comp)
		if crdCount > 0 {
			label += fmt.Sprintf("\\n(%d CRDs)", crdCount)
		}
		b.WriteString(fmt.Sprintf("    %s[\"%s\"]\n", cid, label))
	}
	b.WriteString("\n")

	// Emit edges, deduped
	seenEdges := make(map[string]bool)
	for _, dep := range depGraph {
		from := getStr(dep, "from", "")
		to := getStr(dep, "to", "")
		depType := getStr(dep, "type", "")
		edgeKey := from + "|" + to + "|" + depType
		if seenEdges[edgeKey] {
			continue
		}
		seenEdges[edgeKey] = true

		fromID := sanitizeID(from)
		toID := sanitizeID(to)

		// Ensure target node exists (might be external)
		if !emittedNodes[toID] {
			emittedNodes[toID] = true
			b.WriteString(fmt.Sprintf("    %s[\"%s\"]\n", toID, escapeLabel(to)))
		}

		if strings.HasPrefix(depType, "watches-crd:") {
			crdKind := depType[len("watches-crd:"):]
			b.WriteString(fmt.Sprintf("    %s -->|\"watches %s\"| %s\n",
				fromID, escapeLabel(crdKind), toID))
		} else if depType == "go-module" {
			b.WriteString(fmt.Sprintf("    %s -.->|\"go-module\"| %s\n", fromID, toID))
		} else {
			b.WriteString(fmt.Sprintf("    %s -->|\"%s\"| %s\n",
				fromID, escapeLabel(depType), toID))
		}
	}

	b.WriteString("```\n")
	return b.String()
}

// --- Platform architecture page ---

func renderPlatformArchDocPage(data map[string]interface{}) string {
	var b strings.Builder

	b.WriteString("# Platform Architecture\n\n")

	// CRD Ownership Map
	crds := getSlice(data, "crds")
	crdOwnership := getMap(data, "crd_ownership")

	b.WriteString("## CRD Ownership Map\n\n")
	b.WriteString(fmt.Sprintf("The platform defines %d CRDs. Each CRD is owned by exactly one component.\n\n", len(crds)))

	if crdOwnership != nil {
		// Group by owner
		ownerCRDs := make(map[string][]string)
		for kind, owner := range crdOwnership {
			ownerStr, _ := owner.(string)
			ownerCRDs[ownerStr] = append(ownerCRDs[ownerStr], kind)
		}

		// Sort owners
		owners := make([]string, 0, len(ownerCRDs))
		for o := range ownerCRDs {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		b.WriteString("| Owner | CRDs |\n")
		b.WriteString("|-------|------|\n")
		for _, owner := range owners {
			kinds := ownerCRDs[owner]
			sort.Strings(kinds)
			b.WriteString(fmt.Sprintf("| **%s** | %s |\n", owner, strings.Join(kinds, ", ")))
		}
		b.WriteString("\n")
	}

	// Cross-component dependencies
	depGraph := getSlice(data, "dependency_graph")
	b.WriteString("## Cross-Component Dependencies\n\n")
	if len(depGraph) > 0 {
		b.WriteString("Relationships detected through Go module imports and CRD watch patterns.\n\n")
		b.WriteString("| From | To | Type |\n")
		b.WriteString("|------|----|------|\n")
		for _, dep := range depGraph {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				getStr(dep, "from", ""), getStr(dep, "to", ""),
				getStr(dep, "type", "")))
		}
		b.WriteString("\n")

		// Find tightest coupling
		couplingCounts := make(map[string]int)
		for _, dep := range depGraph {
			from := getStr(dep, "from", "")
			to := getStr(dep, "to", "")
			if from != to {
				key := from + " -> " + to
				couplingCounts[key]++
			}
		}
		maxKey, maxCount := "", 0
		for k, v := range couplingCounts {
			if v > maxCount {
				maxKey, maxCount = k, v
			}
		}
		if maxCount > 1 {
			b.WriteString(fmt.Sprintf("**Tightest coupling:** `%s` (%d dependency edges).\n\n", maxKey, maxCount))
		}
	} else {
		b.WriteString("No cross-component dependencies detected.\n\n")
	}

	return b.String()
}

// --- Platform network page ---

func renderPlatformNetworkDocPage(data map[string]interface{}) string {
	var b strings.Builder

	services := getSlice(data, "services")
	b.WriteString("# Network Topology\n\n")
	b.WriteString(fmt.Sprintf("%d Kubernetes services across the platform.\n\n", len(services)))

	// Service map diagram grouped by component
	if len(services) > 0 {
		b.WriteString("## Service Map\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("graph LR\n")
		b.WriteString("    classDef component fill:#3498db,stroke:#2980b9,color:#fff,stroke-width:2px\n")
		b.WriteString("    classDef webhook fill:#e74c3c,stroke:#c0392b,color:#fff\n")
		b.WriteString("    classDef metrics fill:#f39c12,stroke:#e67e22,color:#fff\n")
		b.WriteString("    classDef data fill:#2ecc71,stroke:#27ae60,color:#fff\n\n")

		// Group services by owner
		ownerServices := make(map[string][]map[string]interface{})
		for _, svc := range services {
			owner := getStr(svc, "owner", "unknown")
			ownerServices[owner] = append(ownerServices[owner], svc)
		}

		owners := make([]string, 0, len(ownerServices))
		for o := range ownerServices {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		svcCounter := 0
		for _, owner := range owners {
			ownerID := sanitizeID(owner)
			b.WriteString(fmt.Sprintf("    subgraph %s_sub[\"%s\"]\n", ownerID, escapeLabel(owner)))
			for _, svc := range ownerServices[owner] {
				svcCounter++
				name := getStr(svc, "name", "")
				ports := getSlice(svc, "ports")
				var portParts []string
				for _, p := range ports {
					portParts = append(portParts, fmt.Sprintf("%v", p["port"]))
				}
				svcID := fmt.Sprintf("svc_%d", svcCounter)
				portStr := strings.Join(portParts, ",")

				// Classify by port pattern
				cls := "data"
				for _, p := range ports {
					port := getInt(p, "port")
					if port == 443 {
						cls = "webhook"
					} else if port == 8443 {
						cls = "metrics"
					}
				}

				b.WriteString(fmt.Sprintf("        %s[\"%s\\n%s\"]:::%s\n",
					svcID, escapeLabel(name), portStr, cls))
			}
			b.WriteString("    end\n")
		}
		b.WriteString("```\n\n")

		// Services table
		b.WriteString("## Services by Component\n\n")
		b.WriteString("| Owner | Service | Ports |\n")
		b.WriteString("|-------|---------|-------|\n")
		for _, owner := range owners {
			for _, svc := range ownerServices[owner] {
				ports := getSlice(svc, "ports")
				var portParts []string
				for _, p := range ports {
					portParts = append(portParts, fmt.Sprintf("%v/%s",
						p["port"], getStr(p, "protocol", "TCP")))
				}
				b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
					owner, getStr(svc, "name", ""), strings.Join(portParts, ", ")))
			}
		}
		b.WriteString("\n")

		// Port patterns
		b.WriteString("## Port Patterns\n\n")
		portGroups := make(map[string][]string)
		for _, svc := range services {
			ports := getSlice(svc, "ports")
			for _, p := range ports {
				port := fmt.Sprintf("%v/TCP", p["port"])
				name := getStr(svc, "name", "")
				portGroups[port] = append(portGroups[port], name)
			}
		}
		portKeys := make([]string, 0, len(portGroups))
		for k := range portGroups {
			portKeys = append(portKeys, k)
		}
		sort.Strings(portKeys)
		for _, port := range portKeys {
			svcs := portGroups[port]
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", port, strings.Join(svcs, ", ")))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// --- Platform RBAC page ---

func renderPlatformRBACDocPage(data map[string]interface{}) string {
	var b strings.Builder

	rbacRoles := getSlice(data, "rbac_cluster_roles")
	b.WriteString("# RBAC Surface\n\n")
	b.WriteString(fmt.Sprintf("%d cluster roles across the platform.\n\n", len(rbacRoles)))

	if len(rbacRoles) > 0 {
		// Permission scope diagram: show components with their broadest roles
		b.WriteString("## Permission Scope by Component\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("graph TD\n")
		b.WriteString("    classDef wide fill:#e74c3c,stroke:#c0392b,color:#fff\n")
		b.WriteString("    classDef medium fill:#f39c12,stroke:#e67e22,color:#fff\n")
		b.WriteString("    classDef narrow fill:#2ecc71,stroke:#27ae60,color:#fff\n")
		b.WriteString("    classDef component fill:#3498db,stroke:#2980b9,color:#fff\n\n")

		// Group by owner, find widest role per owner
		type roleInfo struct {
			name      string
			resources int
		}
		ownerRoles := make(map[string][]roleInfo)
		for _, role := range rbacRoles {
			owner := getStr(role, "owner", "")
			name := getStr(role, "name", "")
			rules := getSlice(role, "rules")
			totalResources := 0
			for _, rule := range rules {
				totalResources += len(getStringSlice(rule, "resources"))
			}
			ownerRoles[owner] = append(ownerRoles[owner], roleInfo{name, totalResources})
		}

		owners := make([]string, 0, len(ownerRoles))
		for o := range ownerRoles {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		roleCounter := 0
		for _, owner := range owners {
			roles := ownerRoles[owner]
			ownerID := sanitizeID(owner)
			b.WriteString(fmt.Sprintf("    %s[\"%s\\n%d roles\"]:::component\n",
				ownerID, escapeLabel(owner), len(roles)))

			// Sort by resource count descending, show top 3
			sort.Slice(roles, func(i, j int) bool {
				return roles[i].resources > roles[j].resources
			})
			limit := 3
			if len(roles) < limit {
				limit = len(roles)
			}
			for _, r := range roles[:limit] {
				roleCounter++
				cls := "narrow"
				if r.resources > 30 {
					cls = "wide"
				} else if r.resources > 10 {
					cls = "medium"
				}
				rID := fmt.Sprintf("role_%d", roleCounter)
				b.WriteString(fmt.Sprintf("    %s --> %s[\"%s\\n%d resource types\"]:::%s\n",
					ownerID, rID, escapeLabel(r.name), r.resources, cls))
			}
			if len(roles) > limit {
				roleCounter++
				rID := fmt.Sprintf("role_%d", roleCounter)
				b.WriteString(fmt.Sprintf("    %s --> %s[\"%d more roles\"]:::narrow\n",
					ownerID, rID, len(roles)-limit))
			}
		}

		b.WriteString("```\n\n")

		// Full table
		b.WriteString("## Roles by Component\n\n")
		b.WriteString("| Owner | Role | Resource Types |\n")
		b.WriteString("|-------|------|----------------|\n")
		for _, owner := range owners {
			for _, r := range ownerRoles[owner] {
				b.WriteString(fmt.Sprintf("| %s | %s | %d |\n", owner, r.name, r.resources))
			}
		}
		b.WriteString("\n")
	}

	return b.String()
}

// --- Platform secrets page ---

func renderPlatformSecretsDocPage(data map[string]interface{}) string {
	var b strings.Builder

	secrets := getSlice(data, "secrets_referenced")
	b.WriteString("# Secrets Inventory\n\n")
	b.WriteString(fmt.Sprintf("%d secrets referenced across the platform. No secret values are extracted, only names, types, and which component references them.\n\n", len(secrets)))

	if len(secrets) > 0 {
		// Distribution diagram
		b.WriteString("## Secret Distribution\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("graph TD\n")
		b.WriteString("    classDef tls fill:#e74c3c,stroke:#c0392b,color:#fff\n")
		b.WriteString("    classDef opaque fill:#f39c12,stroke:#e67e22,color:#fff\n")
		b.WriteString("    classDef component fill:#3498db,stroke:#2980b9,color:#fff\n\n")

		// Group by owner
		ownerSecrets := make(map[string][]map[string]interface{})
		for _, s := range secrets {
			owner := getStr(s, "owner", "unknown")
			ownerSecrets[owner] = append(ownerSecrets[owner], s)
		}

		owners := make([]string, 0, len(ownerSecrets))
		for o := range ownerSecrets {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		secretCounter := 0
		for _, owner := range owners {
			secs := ownerSecrets[owner]
			ownerID := sanitizeID(owner)
			b.WriteString(fmt.Sprintf("    %s[\"%s\\n%d secrets\"]:::component\n",
				ownerID, escapeLabel(owner), len(secs)))

			// Group by type
			tlsNames := make([]string, 0)
			opaqueNames := make([]string, 0)
			for _, s := range secs {
				name := getStr(s, "name", "")
				stype := getStr(s, "type", "Opaque")
				if strings.Contains(stype, "tls") {
					tlsNames = append(tlsNames, name)
				} else {
					opaqueNames = append(opaqueNames, name)
				}
			}

			if len(tlsNames) > 0 {
				secretCounter++
				sID := fmt.Sprintf("sec_%d", secretCounter)
				label := strings.Join(tlsNames, "\\n")
				b.WriteString(fmt.Sprintf("    %s --> %s[\"%s\"]:::tls\n", ownerID, sID, escapeLabel(label)))
			}
			if len(opaqueNames) > 0 {
				secretCounter++
				sID := fmt.Sprintf("sec_%d", secretCounter)
				label := strings.Join(opaqueNames, "\\n")
				b.WriteString(fmt.Sprintf("    %s --> %s[\"%s\"]:::opaque\n", ownerID, sID, escapeLabel(label)))
			}
		}

		b.WriteString("```\n\n")

		// Full table
		b.WriteString("## Secrets by Component\n\n")
		b.WriteString("| Owner | Secret | Type |\n")
		b.WriteString("|-------|--------|------|\n")
		for _, owner := range owners {
			for _, s := range ownerSecrets[owner] {
				b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
					owner, getStr(s, "name", ""), getStr(s, "type", "Opaque")))
			}
		}
		b.WriteString("\n")

		// Patterns
		b.WriteString("## Patterns\n\n")
		webhookCount := 0
		tlsCount := 0
		for _, s := range secrets {
			name := getStr(s, "name", "")
			stype := getStr(s, "type", "")
			if strings.Contains(name, "webhook") || strings.Contains(name, "cert") {
				webhookCount++
			}
			if strings.Contains(stype, "tls") {
				tlsCount++
			}
		}
		if webhookCount > 0 {
			b.WriteString(fmt.Sprintf("- **Webhook certs** are the dominant secret type (%d of %d secrets).\n", webhookCount, len(secrets)))
		}
		if tlsCount > 0 {
			b.WriteString(fmt.Sprintf("- **kubernetes.io/tls** secrets (%d) are used for TLS-terminated services.\n", tlsCount))
		}
		b.WriteString("\n")
	}

	return b.String()
}
