package renderer

import (
	"fmt"
	"sort"
	"strings"
)

// renderPlatformDocs generates a complete docs site from aggregated platform data.
func renderPlatformDocs(data map[string]interface{}) []DocsPage {
	var pages []DocsPage

	pages = append(pages, DocsPage{
		Path:    "index.md",
		Content: renderPlatformIndexDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "platform-architecture.md",
		Content: renderPlatformArchDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "network-topology.md",
		Content: renderPlatformNetworkDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "rbac-surface.md",
		Content: renderPlatformRBACDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "secrets-inventory.md",
		Content: renderPlatformSecretsDocPage(data),
	})

	// Per-component deep dive pages (dedup by component name)
	componentDataList := getSlice(data, "component_data")
	seenComps := make(map[string]bool)
	for _, compData := range componentDataList {
		compName := getStr(compData, "component", "")
		if compName == "" || seenComps[compName] {
			continue
		}
		seenComps[compName] = true
		compPages := renderComponentDocs(compData, "components/"+sanitizeID(compName))
		pages = append(pages, compPages...)
	}

	return pages
}

// --- Platform index page ---

func renderPlatformIndexDocPage(data map[string]interface{}) string {
	var b strings.Builder

	platformName := getStr(data, "platform", "Platform")
	components := getStringSlice(data, "components")
	crds := getSlice(data, "crds")
	services := getSlice(data, "services")
	secrets := getSlice(data, "secrets_referenced")
	rbacRoles := getSlice(data, "rbac_cluster_roles")
	depGraph := getSlice(data, "dependency_graph")

	b.WriteString(fmt.Sprintf("# %s Platform Analysis\n\n", platformName))
	b.WriteString("*Generated by rhoai-architecture-analyzer. All data produced by deterministic static analysis.*\n\n")

	// Summary
	b.WriteString("## Platform Summary\n\n")
	b.WriteString("| Metric | Count |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Components | %d |\n", len(components)))
	b.WriteString(fmt.Sprintf("| CRDs | %d |\n", len(crds)))
	b.WriteString(fmt.Sprintf("| Services | %d |\n", len(services)))
	b.WriteString(fmt.Sprintf("| Secrets | %d |\n", len(secrets)))
	b.WriteString(fmt.Sprintf("| Cluster Roles | %d |\n", len(rbacRoles)))
	b.WriteString(fmt.Sprintf("| Cross-Component Dependencies | %d |\n", len(depGraph)))
	b.WriteString("\n")

	// Component dependency graph
	b.WriteString("## Component Dependency Graph\n\n")
	b.WriteString(renderPlatformDepGraphMermaid(data))
	b.WriteString("\n")

	// Component list
	b.WriteString("## Components Analyzed\n\n")
	if len(components) > 0 {
		sorted := make([]string, len(components))
		copy(sorted, components)
		sort.Strings(sorted)

		// Count CRDs per component
		crdCounts := make(map[string]int)
		for _, crd := range crds {
			owner := getStr(crd, "owner", "")
			crdCounts[owner]++
		}

		b.WriteString("| Component | CRDs |\n")
		b.WriteString("|-----------|------|\n")
		for _, comp := range sorted {
			count := crdCounts[comp]
			b.WriteString(fmt.Sprintf("| %s | %d |\n", comp, count))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderPlatformDepGraphMermaid builds a clean dependency graph showing only connected components.
// Multi-edges between the same pair are collapsed into a single edge with a summary label.
func renderPlatformDepGraphMermaid(data map[string]interface{}) string {
	var b strings.Builder

	components := getStringSlice(data, "components")
	depGraph := getSlice(data, "dependency_graph")
	componentSet := make(map[string]bool)
	for _, c := range components {
		componentSet[c] = true
	}

	// Collapse edges: group by from|to pair, collect types
	type edgePair struct{ from, to string }
	edgeTypes := make(map[edgePair][]string)
	edgeOrder := make([]edgePair, 0)
	for _, dep := range depGraph {
		from := getStr(dep, "from", "")
		to := getStr(dep, "to", "")
		depType := getStr(dep, "type", "")
		if from == to { // skip self-references
			continue
		}
		pair := edgePair{from, to}
		if _, exists := edgeTypes[pair]; !exists {
			edgeOrder = append(edgeOrder, pair)
		}
		edgeTypes[pair] = append(edgeTypes[pair], depType)
	}

	if len(edgeTypes) == 0 {
		return ""
	}

	// Collect only nodes that participate in at least one edge
	connectedNodes := make(map[string]bool)
	for pair := range edgeTypes {
		connectedNodes[pair.from] = true
		connectedNodes[pair.to] = true
	}

	crdCounts := make(map[string]int)
	for _, crd := range getSlice(data, "crds") {
		owner := getStr(crd, "owner", "")
		crdCounts[owner]++
	}

	b.WriteString("```mermaid\n")
	b.WriteString("graph LR\n")
	b.WriteString("    classDef internal fill:#3498db,stroke:#2980b9,color:#fff\n")
	b.WriteString("    classDef external fill:#95a5a6,stroke:#7f8c8d,color:#fff\n\n")

	// Emit connected nodes only
	emitted := make(map[string]bool)
	sortedNodes := make([]string, 0, len(connectedNodes))
	for n := range connectedNodes {
		sortedNodes = append(sortedNodes, n)
	}
	sort.Strings(sortedNodes)

	for _, comp := range sortedNodes {
		cid := sanitizeID(comp)
		if emitted[cid] {
			continue
		}
		emitted[cid] = true
		label := escapeLabel(comp)
		cls := "internal"
		if !componentSet[comp] {
			cls = "external"
		} else if crdCounts[comp] > 0 {
			label += fmt.Sprintf("\\n%d CRDs", crdCounts[comp])
		}
		b.WriteString(fmt.Sprintf("    %s[\"%s\"]:::%s\n", cid, label, cls))
	}
	b.WriteString("\n")

	// Emit collapsed edges
	for _, pair := range edgeOrder {
		types := edgeTypes[pair]
		fromID := sanitizeID(pair.from)
		toID := sanitizeID(pair.to)

		// Count watches, go-module, and uses-image separately
		watches := make([]string, 0)
		hasGoMod := false
		hasUsesImage := false
		other := make([]string, 0)
		for _, t := range types {
			if strings.HasPrefix(t, "watches-crd:") {
				watches = append(watches, t[len("watches-crd:"):])
			} else if t == "go-module" {
				hasGoMod = true
			} else if t == "uses-image" {
				hasUsesImage = true
			} else {
				other = append(other, t)
			}
		}

		if hasGoMod {
			b.WriteString(fmt.Sprintf("    %s -.->|\"go-module\"| %s\n", fromID, toID))
		}
		if hasUsesImage {
			b.WriteString(fmt.Sprintf("    %s -->|\"sidecar\"| %s\n", fromID, toID))
		}
		if len(watches) > 0 {
			label := fmt.Sprintf("watches %d CRDs", len(watches))
			if len(watches) <= 2 {
				label = "watches " + strings.Join(watches, ", ")
			}
			b.WriteString(fmt.Sprintf("    %s ==>|\"%s\"| %s\n", fromID, escapeLabel(label), toID))
		}
		for _, t := range other {
			b.WriteString(fmt.Sprintf("    %s -->|\"%s\"| %s\n", fromID, escapeLabel(t), toID))
		}
	}

	b.WriteString("```\n")
	return b.String()
}

// --- Platform architecture page ---

func renderPlatformArchDocPage(data map[string]interface{}) string {
	var b strings.Builder

	b.WriteString("# Platform Architecture\n\n")

	// CRD Ownership Map
	crds := getSlice(data, "crds")
	crdOwnership := getMap(data, "crd_ownership")

	b.WriteString("## CRD Ownership Map\n\n")
	b.WriteString(fmt.Sprintf("The platform defines %d CRDs. Each CRD is owned by exactly one component.\n\n", len(crds)))

	if crdOwnership != nil {
		// Group by owner
		ownerCRDs := make(map[string][]string)
		for kind, owner := range crdOwnership {
			ownerStr, _ := owner.(string)
			ownerCRDs[ownerStr] = append(ownerCRDs[ownerStr], kind)
		}

		// Sort owners
		owners := make([]string, 0, len(ownerCRDs))
		for o := range ownerCRDs {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		b.WriteString("| Owner | CRDs |\n")
		b.WriteString("|-------|------|\n")
		for _, owner := range owners {
			kinds := ownerCRDs[owner]
			sort.Strings(kinds)
			b.WriteString(fmt.Sprintf("| **%s** | %s |\n", owner, strings.Join(kinds, ", ")))
		}
		b.WriteString("\n")
	}

	// Cross-component dependencies
	depGraph := getSlice(data, "dependency_graph")
	b.WriteString("## Cross-Component Dependencies\n\n")
	if len(depGraph) > 0 {
		b.WriteString("Relationships detected through Go module imports and CRD watch patterns.\n\n")
		b.WriteString("| From | To | Type |\n")
		b.WriteString("|------|----|------|\n")
		for _, dep := range depGraph {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				getStr(dep, "from", ""), getStr(dep, "to", ""),
				getStr(dep, "type", "")))
		}
		b.WriteString("\n")

		// Find tightest coupling
		couplingCounts := make(map[string]int)
		for _, dep := range depGraph {
			from := getStr(dep, "from", "")
			to := getStr(dep, "to", "")
			if from != to {
				key := from + " -> " + to
				couplingCounts[key]++
			}
		}
		maxKey, maxCount := "", 0
		for k, v := range couplingCounts {
			if v > maxCount {
				maxKey, maxCount = k, v
			}
		}
		if maxCount > 1 {
			b.WriteString(fmt.Sprintf("**Tightest coupling:** `%s` (%d dependency edges).\n\n", maxKey, maxCount))
		}
	} else {
		b.WriteString("No cross-component dependencies detected.\n\n")
	}

	return b.String()
}

// --- Platform network page ---

func renderPlatformNetworkDocPage(data map[string]interface{}) string {
	var b strings.Builder

	services := getSlice(data, "services")
	b.WriteString("# Network Topology\n\n")
	b.WriteString(fmt.Sprintf("%d Kubernetes services across the platform.\n\n", len(services)))

	// Service map diagram grouped by component, with cross-component links
	if len(services) > 0 {
		b.WriteString("## Service Map\n\n")
		b.WriteString("Services grouped by owning component. Dashed arrows show cross-component references (component A deploys or references a service defined by component B).\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("graph LR\n")
		b.WriteString("    classDef webhook fill:#e74c3c,stroke:#c0392b,color:#fff\n")
		b.WriteString("    classDef metrics fill:#f39c12,stroke:#e67e22,color:#fff\n")
		b.WriteString("    classDef data fill:#2ecc71,stroke:#27ae60,color:#fff\n\n")

		// Group services by owner
		ownerServices := make(map[string][]map[string]interface{})
		for _, svc := range services {
			owner := getStr(svc, "owner", "unknown")
			ownerServices[owner] = append(ownerServices[owner], svc)
		}

		owners := make([]string, 0, len(ownerServices))
		for o := range ownerServices {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		// Build service name -> (owner, svcID) map for cross-linking
		type svcRef struct {
			owner string
			svcID string
		}
		svcNameMap := make(map[string][]svcRef)

		svcCounter := 0
		for _, owner := range owners {
			ownerID := sanitizeID(owner)
			b.WriteString(fmt.Sprintf("    subgraph %s_sub[\"%s\"]\n", ownerID, escapeLabel(owner)))
			for _, svc := range ownerServices[owner] {
				svcCounter++
				name := getStr(svc, "name", "")
				ports := getSlice(svc, "ports")
				var portParts []string
				for _, p := range ports {
					portParts = append(portParts, fmt.Sprintf("%v", p["port"]))
				}
				svcID := fmt.Sprintf("svc_%d", svcCounter)
				portStr := strings.Join(portParts, ",")

				// Classify by port pattern
				cls := "data"
				for _, p := range ports {
					port := getInt(p, "port")
					if port == 443 {
						cls = "webhook"
					} else if port == 8443 {
						cls = "metrics"
					}
				}

				b.WriteString(fmt.Sprintf("        %s[\"%s\\n%s\"]:::%s\n",
					svcID, escapeLabel(name), portStr, cls))

				svcNameMap[name] = append(svcNameMap[name], svcRef{owner, svcID})
			}
			b.WriteString("    end\n")
		}

		// Cross-component links: when the same service name appears in multiple components
		b.WriteString("\n    %% Cross-component service references\n")
		for name, refs := range svcNameMap {
			if len(refs) < 2 {
				continue
			}
			// Skip generic names that don't represent real cross-component refs
			if name == "webhook-service" || name == "kube-rbac-proxy" || name == "service" {
				continue
			}
			// Link secondary references to the primary (first alphabetically by owner)
			sort.Slice(refs, func(i, j int) bool { return refs[i].owner < refs[j].owner })
			primaryRef := refs[0]
			for _, ref := range refs[1:] {
				b.WriteString(fmt.Sprintf("    %s -.->|\"refs %s\"| %s\n",
					ref.svcID, escapeLabel(name), primaryRef.svcID))
			}
		}

		b.WriteString("```\n\n")

		// Services table
		b.WriteString("## Services by Component\n\n")
		b.WriteString("| Owner | Service | Ports |\n")
		b.WriteString("|-------|---------|-------|\n")
		for _, owner := range owners {
			for _, svc := range ownerServices[owner] {
				ports := getSlice(svc, "ports")
				var portParts []string
				for _, p := range ports {
					portParts = append(portParts, fmt.Sprintf("%v/%s",
						p["port"], getStr(p, "protocol", "TCP")))
				}
				b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
					owner, getStr(svc, "name", ""), strings.Join(portParts, ", ")))
			}
		}
		b.WriteString("\n")

		// Port patterns
		b.WriteString("## Port Patterns\n\n")
		portGroups := make(map[string][]string)
		for _, svc := range services {
			ports := getSlice(svc, "ports")
			for _, p := range ports {
				port := fmt.Sprintf("%v/TCP", p["port"])
				name := getStr(svc, "name", "")
				portGroups[port] = append(portGroups[port], name)
			}
		}
		portKeys := make([]string, 0, len(portGroups))
		for k := range portGroups {
			portKeys = append(portKeys, k)
		}
		sort.Strings(portKeys)
		for _, port := range portKeys {
			svcs := portGroups[port]
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", port, strings.Join(svcs, ", ")))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// --- Platform RBAC page ---

func renderPlatformRBACDocPage(data map[string]interface{}) string {
	var b strings.Builder

	rbacRoles := getSlice(data, "rbac_cluster_roles")
	b.WriteString("# RBAC Surface\n\n")
	b.WriteString(fmt.Sprintf("%d cluster roles across the platform.\n\n", len(rbacRoles)))

	if len(rbacRoles) > 0 {
		// Permission scope summary: one bar per component showing role count and max breadth
		type roleInfo struct {
			name      string
			resources int
		}
		ownerRoles := make(map[string][]roleInfo)
		for _, role := range rbacRoles {
			owner := getStr(role, "owner", "")
			name := getStr(role, "name", "")
			rules := getSlice(role, "rules")
			totalResources := 0
			for _, rule := range rules {
				totalResources += len(getStringSlice(rule, "resources"))
			}
			ownerRoles[owner] = append(ownerRoles[owner], roleInfo{name, totalResources})
		}

		owners := make([]string, 0, len(ownerRoles))
		for o := range ownerRoles {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		b.WriteString("## Permission Scope by Component\n\n")
		b.WriteString("Each bar shows the widest role (by resource type count). Color indicates scope: ")
		b.WriteString(":red_circle: wide (>30 resources), :orange_circle: medium (10-30), :green_circle: narrow (<10).\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '14px'}}}%%\n")
		b.WriteString("xychart-beta\n")
		b.WriteString("    title \"Widest Role Scope (resource types)\"\n")
		b.WriteString("    x-axis [")

		// Build x-axis labels and data
		labels := make([]string, 0, len(owners))
		values := make([]int, 0, len(owners))
		for _, owner := range owners {
			roles := ownerRoles[owner]
			maxRes := 0
			for _, r := range roles {
				if r.resources > maxRes {
					maxRes = r.resources
				}
			}
			// Shorten label for readability
			shortName := owner
			if len(shortName) > 20 {
				shortName = shortName[:18] + ".."
			}
			labels = append(labels, fmt.Sprintf("\"%s\"", shortName))
			values = append(values, maxRes)
		}
		b.WriteString(strings.Join(labels, ", "))
		b.WriteString("]\n")
		b.WriteString("    y-axis \"Resource types\" 0 --> ")
		maxVal := 0
		for _, v := range values {
			if v > maxVal {
				maxVal = v
			}
		}
		b.WriteString(fmt.Sprintf("%d\n", maxVal+5))
		b.WriteString("    bar [")
		valStrs := make([]string, len(values))
		for i, v := range values {
			valStrs[i] = fmt.Sprintf("%d", v)
		}
		b.WriteString(strings.Join(valStrs, ", "))
		b.WriteString("]\n")
		b.WriteString("```\n\n")

		// Summary table: component, role count, widest role name, resource count
		b.WriteString("## Roles by Component\n\n")
		b.WriteString("| Component | Roles | Widest Role | Resources | Scope |\n")
		b.WriteString("|-----------|-------|-------------|-----------|-------|\n")
		for _, owner := range owners {
			roles := ownerRoles[owner]
			sort.Slice(roles, func(i, j int) bool {
				return roles[i].resources > roles[j].resources
			})
			widest := roles[0]
			scope := "narrow"
			if widest.resources > 30 {
				scope = "**wide**"
			} else if widest.resources > 10 {
				scope = "medium"
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %s | %d | %s |\n",
				owner, len(roles), widest.name, widest.resources, scope))
		}
		b.WriteString("\n")

		// Detailed expandable section for full role list
		b.WriteString("<details>\n<summary>Full role details</summary>\n\n")
		b.WriteString("| Owner | Role | Resource Types |\n")
		b.WriteString("|-------|------|----------------|\n")
		for _, owner := range owners {
			roles := ownerRoles[owner]
			sort.Slice(roles, func(i, j int) bool {
				return roles[i].resources > roles[j].resources
			})
			for _, r := range roles {
				b.WriteString(fmt.Sprintf("| %s | %s | %d |\n", owner, r.name, r.resources))
			}
		}
		b.WriteString("\n</details>\n\n")
	}

	return b.String()
}

// --- Platform secrets page ---

func renderPlatformSecretsDocPage(data map[string]interface{}) string {
	var b strings.Builder

	secrets := getSlice(data, "secrets_referenced")
	b.WriteString("# Secrets Inventory\n\n")
	b.WriteString(fmt.Sprintf("%d secrets referenced across the platform. No secret values are extracted, only names, types, and which component references them.\n\n", len(secrets)))

	if len(secrets) > 0 {
		// Group by owner
		ownerSecrets := make(map[string][]map[string]interface{})
		for _, s := range secrets {
			owner := getStr(s, "owner", "unknown")
			ownerSecrets[owner] = append(ownerSecrets[owner], s)
		}

		owners := make([]string, 0, len(ownerSecrets))
		for o := range ownerSecrets {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		// Compact bar chart: secrets per component, stacked by type
		b.WriteString("## Secret Distribution\n\n")
		b.WriteString("```mermaid\n")
		b.WriteString("%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '14px'}}}%%\n")
		b.WriteString("xychart-beta\n")
		b.WriteString("    title \"Secrets per Component\"\n")
		b.WriteString("    x-axis [")
		labels := make([]string, 0, len(owners))
		totalVals := make([]int, 0, len(owners))
		for _, owner := range owners {
			shortName := owner
			if len(shortName) > 20 {
				shortName = shortName[:18] + ".."
			}
			labels = append(labels, fmt.Sprintf("\"%s\"", shortName))
			totalVals = append(totalVals, len(ownerSecrets[owner]))
		}
		b.WriteString(strings.Join(labels, ", "))
		b.WriteString("]\n")
		maxVal := 0
		for _, v := range totalVals {
			if v > maxVal {
				maxVal = v
			}
		}
		b.WriteString(fmt.Sprintf("    y-axis \"Secrets\" 0 --> %d\n", maxVal+2))
		b.WriteString("    bar [")
		valStrs := make([]string, len(totalVals))
		for i, v := range totalVals {
			valStrs[i] = fmt.Sprintf("%d", v)
		}
		b.WriteString(strings.Join(valStrs, ", "))
		b.WriteString("]\n")
		b.WriteString("```\n\n")

		// Summary table
		b.WriteString("## Secrets by Component\n\n")
		b.WriteString("| Component | TLS | Opaque | Total |\n")
		b.WriteString("|-----------|-----|--------|-------|\n")
		for _, owner := range owners {
			tlsCount := 0
			opaqueCount := 0
			for _, s := range ownerSecrets[owner] {
				stype := getStr(s, "type", "Opaque")
				if strings.Contains(stype, "tls") {
					tlsCount++
				} else {
					opaqueCount++
				}
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %d | %d |\n",
				owner, tlsCount, opaqueCount, tlsCount+opaqueCount))
		}
		b.WriteString("\n")

		// Detailed secret list in expandable section
		b.WriteString("<details>\n<summary>Full secret inventory</summary>\n\n")
		b.WriteString("| Owner | Secret | Type |\n")
		b.WriteString("|-------|--------|------|\n")
		for _, owner := range owners {
			for _, s := range ownerSecrets[owner] {
				b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
					owner, getStr(s, "name", ""), getStr(s, "type", "Opaque")))
			}
		}
		b.WriteString("\n</details>\n\n")

		// Patterns
		b.WriteString("## Patterns\n\n")
		webhookCount := 0
		tlsCount := 0
		for _, s := range secrets {
			name := getStr(s, "name", "")
			stype := getStr(s, "type", "")
			if strings.Contains(name, "webhook") || strings.Contains(name, "cert") {
				webhookCount++
			}
			if strings.Contains(stype, "tls") {
				tlsCount++
			}
		}
		if webhookCount > 0 {
			b.WriteString(fmt.Sprintf("- **Webhook certs** are the dominant secret type (%d of %d secrets).\n", webhookCount, len(secrets)))
		}
		if tlsCount > 0 {
			b.WriteString(fmt.Sprintf("- **kubernetes.io/tls** secrets (%d) are used for TLS-terminated services.\n", tlsCount))
		}
		b.WriteString("\n")
	}

	return b.String()
}
